language: java
matrix:
  fast_finish: true
  include:
    # unit tests (openjdk11)
    - jdk: openjdk11
      env:
        - DESC="openjdk11 unit tests"
        - CMD="mvn clean test jacoco:report coveralls:jacoco -Dcheckstyle.skip=true"
        - LANG=en_US.utf8